import type { GameLocation } from "../shared/game.js";

export const locations: GameLocation[] = [
  {
    id: "pripyat-square",
    lat: 51.40656998663626,
    lng: 30.05699592605194,
    country: "Ukraine",
    region: "Kyiv Oblast",
    label: "Pripyat Empty Square",
    category: "Horror",
    sceneProfile: "wide-open",
    clueDensity: "high",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 45, pitch: 0, fov: 82, panoId: "HyxCm9FuAiw2z4ORcSYa9w" },
  },
  {
    id: "buzludzha-monument",
    lat: 42.73514941026769,
    lng: 25.39296914503926,
    country: "Bulgaria",
    region: "Stara Zagora",
    label: "Abandoned Mountain Monument",
    category: "Horror",
    sceneProfile: "landmark",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 12, pitch: 2, fov: 86, panoId: "CAoSFkNJSE0wb2dLRUlDQWdJQzdqTXpqTHc." },
  },
  {
    id: "beelitz-hospital",
    lat: 52.26091979419143,
    lng: 12.92292203887398,
    country: "Germany",
    region: "Brandenburg",
    label: "Old Hospital Grounds",
    category: "Horror",
    sceneProfile: "claustrophobic",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 128, pitch: 0, fov: 84, panoId: "CAoSFkNJSE0wb2dLRUlDQWdJQ0stWnZoR2c." },
  },
  {
    id: "hashima-island",
    lat: 32.62776149913295,
    lng: 129.7381996706687,
    country: "Japan",
    region: "Nagasaki",
    label: "Abandoned Island Corridor",
    category: "Industrial",
    sceneProfile: "claustrophobic",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 246, pitch: 0, fov: 82, panoId: "0ponf2aAI41t_u5QoZJ8sQ" },
  },
  {
    id: "tokyo-omoide-yokocho",
    lat: 35.69379502379952,
    lng: 139.7005137408506,
    country: "Japan",
    region: "Tokyo",
    label: "Narrow Neon Alley",
    category: "Urban",
    sceneProfile: "claustrophobic",
    clueDensity: "high",
    peoplePolicy: "needs-review",
    status: "active",
    streetView: { heading: 208, pitch: 0, fov: 76, panoId: "xVZ8qzfNlNz0e43LVztFFg" },
  },
  {
    id: "seoul-euljiro",
    lat: 37.56596110636422,
    lng: 126.9920585355454,
    country: "South Korea",
    region: "Seoul",
    label: "Late Industrial Backstreet",
    category: "Urban",
    sceneProfile: "street-clue",
    clueDensity: "high",
    peoplePolicy: "needs-review",
    status: "active",
    streetView: { heading: 92, pitch: 0, fov: 78, panoId: "IE2wjSLh4WgDA-7RrALViQ" },
  },
  {
    id: "taipei-market-edge",
    lat: 25.08809491689563,
    lng: 121.5250263797674,
    country: "Taiwan",
    region: "Taipei",
    label: "Market Street Under Fluorescent Signs",
    category: "Urban",
    sceneProfile: "street-clue",
    clueDensity: "high",
    peoplePolicy: "needs-review",
    status: "active",
    streetView: { heading: 318, pitch: 0, fov: 78, panoId: "rWn5tyVE6ndi6gt0rFp_9Q" },
  },
  {
    id: "hong-kong-backstreet",
    lat: 22.28205479199495,
    lng: 114.1529630298581,
    country: "Hong Kong",
    region: "Central",
    label: "Dense Hillside Backstreet",
    category: "Liminal",
    sceneProfile: "claustrophobic",
    clueDensity: "high",
    peoplePolicy: "needs-review",
    status: "active",
    streetView: { heading: 160, pitch: -1, fov: 76, panoId: "j8iyJBXY2kvagIJkTJ3YlA" },
  },
  {
    id: "bombay-beach",
    lat: 33.35065675123408,
    lng: -115.7289578671253,
    country: "United States",
    region: "California",
    label: "Deserted Salton Sea Street",
    category: "Horror",
    sceneProfile: "wide-open",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 298, pitch: 0, fov: 84, panoId: "HxNxwRTcXHJ8m--L8n3CJQ" },
  },
  {
    id: "centralia-empty-road",
    lat: 40.80337768066074,
    lng: -76.34074441182804,
    country: "United States",
    region: "Pennsylvania",
    label: "Quiet Coal Town Road",
    category: "Horror",
    sceneProfile: "wide-open",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 46, pitch: 0, fov: 82, panoId: "aWLBt2_PKFXpltNIkzrmyg" },
  },
  {
    id: "nagoro-village",
    lat: 33.87058713316603,
    lng: 134.081513929852,
    country: "Japan",
    region: "Tokushima",
    label: "Mountain Village Road",
    category: "Liminal",
    sceneProfile: "street-clue",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 108, pitch: 0, fov: 82, panoId: "bF75CG7W-3cg6uhSla_C6g" },
  },
  {
    id: "oradour-ruins",
    lat: 45.93093715399971,
    lng: 1.031546435813143,
    country: "France",
    region: "Nouvelle-Aquitaine",
    label: "Preserved Ruined Village",
    category: "Horror",
    sceneProfile: "claustrophobic",
    clueDensity: "high",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 238, pitch: 0, fov: 84, panoId: "7pEdX7bv46CYAw2FB2mMFA" },
  },
  {
    id: "chiatura-cable-town",
    lat: 42.28873043777556,
    lng: 43.28153425467744,
    country: "Georgia",
    region: "Imereti",
    label: "Soviet Cable-Car Town",
    category: "Industrial",
    sceneProfile: "landmark",
    clueDensity: "high",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 276, pitch: 0, fov: 82, panoId: "wd5T9OugMYWYr3HRCWqGow" },
  },
  {
    id: "linnahall-tallinn",
    lat: 59.44578821065971,
    lng: 24.75303007355557,
    country: "Estonia",
    region: "Tallinn",
    label: "Concrete Harbor Megastructure",
    category: "Liminal",
    sceneProfile: "wide-open",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 186, pitch: 0, fov: 84, panoId: "mpXPLmEka-OdkpvUVVvB1g" },
  },
  {
    id: "shipka-road",
    lat: 42.74911642155132,
    lng: 25.3211932446101,
    country: "Bulgaria",
    region: "Gabrovo",
    label: "Foggy Mountain Monument Road",
    category: "Nature",
    sceneProfile: "wide-open",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 350, pitch: 0, fov: 84, panoId: "jv5uq4ADD6RWQ32uVZfCPA" },
  },
  {
    id: "industrial-germany-edge",
    lat: 51.4982087567019,
    lng: 6.765314727795631,
    country: "Germany",
    region: "North Rhine-Westphalia",
    label: "Unknown Industrial Area",
    category: "Industrial",
    sceneProfile: "claustrophobic",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 238, pitch: -2, fov: 82, panoId: "pJ0zHPSZr2rcapSmqkAlGg" },
  },
  {
    id: "horror-faroe-road",
    lat: 62.10793149467525,
    lng: -7.031148895126815,
    country: "Faroe Islands",
    region: "Streymoy",
    label: "Remote North Atlantic Road",
    category: "Horror",
    sceneProfile: "wide-open",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 18, pitch: 1, fov: 88, panoId: "-ceHnBWHqy8l91dljfDnmQ" },
  },
  {
    id: "nature-norway-atlantic",
    lat: 63.01677588533239,
    lng: 7.354540866796061,
    country: "Norway",
    region: "More og Romsdal",
    label: "Windblown Coastal Road",
    category: "Nature",
    sceneProfile: "wide-open",
    clueDensity: "medium",
    peoplePolicy: "verified-empty",
    status: "active",
    streetView: { heading: 172, pitch: 0, fov: 84, panoId: "dwjWvjXPsDZIHoYs2BDYow" },
  },
];
